### ISSUE TITLE
Error in setting up MITIE - Win 8.1 Py 3.5

### ISSUE THREAD

**Issue by willemchua** [mit-nlp/MITIE#114]
Hi, I'm currently using Python 3.5 64-bit in Windows 8.1 and I also encountered the same problem. I can't do the pip install git, so I used cmake. I already used all the commands given in the readme. But then, I don't know what to do next after the build's successful.

I tried to change to Python 2.7 64-bit and Python 3.5 32-bit and the same problem with pip install and cmake still occurs.

Here's the error after I've finished the build and tried to run ner.py from the example

```
Traceback (most recent call last):
  File "ner.py", line 14, in <module>
    from mitie import *
  File "C:\Users\ASUS\Desktop\Chatbot\MITIE-master\examples\python/../../mitielib\mitie.py", line 36, in <module>
    _f = ctypes.CDLL(most_recent)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

```

Here's the error when I tried to use pip install git

```
Collecting git+https://github.com/mit-nlp/MITIE.git
  Cloning https://github.com/mit-nlp/MITIE.git to c:\users\asus\appdata\local\temp\pip-5070br-build
Installing collected packages: mitie
  Running setup.py install for mitie ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\asus\\appdata\\local\\temp\\pip-5070br
-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" ins
tall --record c:\users\asus\appdata\local\temp\pip-qfsm1e-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    error: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\asus\\appdata\\local\\temp\\pip-5070br-build\\setup.py';f=geta
ttr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\a
sus\appdata\local\temp\pip-qfsm1e-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\asus\a
ppdata\local\temp\pip-5070br-build\

```

And here's the error when I tried to build it manually through setup.py

```
running install
running build
'make' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    'License :: Boost License',
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\distutils\command\install.py", line 563, in run
    self.run_command('build')
  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 10, in run
    subprocess.check_call(['make', 'mitielib'], shell = True)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'mitielib']' returned non-zero exit status 1
```

Sorry for the long post and/or if this has been answered before.

And thanks in advance, any help's appreciated. :)

**Comment by davisking** [comment]
Did you run these commands?  What happens when you run them?

```
cd mitielib
mkdir build
cd build
cmake ..
cmake --build . --config Release --target install
```

**Comment by willemchua** [comment]
Here's what happened when I ran the cmake ..

```
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.23506.0
-- The CXX compiler identification is MSVC 19.0.23506.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Searching for BLAS and LAPACK
-- Check for STD namespace
-- Check for STD namespace - found
-- Looking for C++ include iostream
-- Looking for C++ include iostream - found
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/ASUS/Desktop/Chatbot/MITIE-master/mitielib/build
```

and when I ran the cmake --build . --config Release --target install, it went to a long installation and finished off with

```
assign_helper': function assumed not to throw an exception but does [C:\Users\ASUS\Desktop\Cha
tbot\MITIE-master\mitielib\build\mitie.vcxproj]
  c:\users\asus\desktop\chatbot\mitie-master\dlib\dlib\matrix/matrix.h(1598): warning C4297: 'dlib::matrix<T,2,1,dlib::default_memory_manager,dlib::r
ow_major_layout>::literal_assign_helper::~literal_assign_helper': function assumed not to throw an exception but does [C:\Users\ASUS\Desktop\Chatbot\
MITIE-master\mitielib\build\mitie.vcxproj]

    157 Warning(s)
    0 Error(s)

Time Elapsed 00:02:07.46
```

And when I tried to run the ner.py, the first error still happened

**Comment by davisking** [comment]
Is there a mitie.dll in the mitielib folder?  The messages you posted indicated that it was built so it should be there.  So I don't see how you can still be getting the errors about not being able to find mitie.dll.

**Comment by danwilhelm** [comment]
Because you're using 64-bit Python, ensure you're compiling 64-bit DLLs:

```
cmake -G "Visual Studio 14 2015 Win64" ..
```

**Comment by davisking** [comment]
Yes. Good point. You definitely need to do that as well.

**Comment by willemchua** [comment]
Thanks, the last command seemed to do the trick.

:D
