### ISSUE TITLE
Windows: OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by AdamMiltonBarker** [mit-nlp/MITIE#152]
Have been battling this for a while, could anyone offer any suggestion. TIA

```
mitielib\mitie.py", line 36, in <module>
    _f = ctypes.CDLL(most_recent)
  File "D:\Installations\Python\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by AdamMiltonBarker** [comment]
Playing around with mitie.py files is empty although mitie.dll exists.

**Comment by AdamMiltonBarker** [comment]
Printing out files in mitie.py gives:

D:\Installations\Mitie\MITIE-master\MITIE-master\mitielib/mitie.dll

Which is correct and a valid path.

**Comment by AdamMiltonBarker** [comment]
I think the solution here solves it, checking now.

https://github.com/mit-nlp/MITIE/issues/150

**Comment by AdamMiltonBarker** [comment]
Sorted that was it.

**Comment by Tanukaroy4494** [comment]
What i tried is 
1) Downloading Anaconda from [https://repo.continuum.io/archive/Anaconda3-5.3.1-Windows-x86_64.exe](url)
2) Go to Anaconda Prompt and downgrade the version to 3.6 using command
**conda install python=3.6.8**

**Comment by paahaadi** [comment]
> What i tried is
> 
> 1. Downloading Anaconda from [https://repo.continuum.io/archive/Anaconda3-5.3.1-Windows-x86_64.exe](url)
> 2. Go to Anaconda Prompt and downgrade the version to 3.6 using command
>    **conda install python=3.6.8**
> 
> It worked for me

%%worked for me too thanks alot.

**Comment by Shreybanugariya** [comment]
i```
mport pyttsx3


engine = pyttsx3.init('sapi5')
voices = engine.getProperty('voices')
print(voices)

def speak(audio):
  pass
```

for the above code there is this error:

PS F:\My stuff\Projects\Virtual Assistant> & C:/Python38/python.exe "f:/My stuff/Projects/Virtual Assistant/practice.py"
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Python38\lib\weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:/My stuff/Projects/Virtual Assistant/practice.py", line 4, in <module>
    engine = pyttsx3.init('sapi5')
  File "C:\Python38\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Python38\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Python38\lib\site-packages\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Python38\lib\site-packages\pyttsx3\drivers\sapi5.py", line 1, in <module>
    import comtypes.client  # Importing comtypes.client will make the gen subpackage
  File "C:\Python38\lib\site-packages\comtypes\__init__.py", line 1176, in <module>
  File "C:\Python38\lib\site-packages\comtypes\__init__.py", line 1180, in IPersist
    COMMETHOD([], HRESULT, 'GetClassID',
  File "C:\Python38\lib\site-packages\comtypes\__init__.py", line 1099, in COMMETHOD
    from comtypes.automation import VARIANT
  File "C:\Python38\lib\site-packages\comtypes\automation.py", line 12, in <module>
    from comtypes import npsupport
  File "C:\Python38\lib\site-packages\comtypes\npsupport.py", line 5, in <module>
    import numpy
    from . import _distributor_init
  File "C:\Python38\lib\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
