### ISSUE TITLE
mitie installation issue in ubuntu

### ISSUE THREAD

**Issue by AP8050** [mit-nlp/MITIE#158]
Issue:
Unable to install mitie.while installing I am getting this error.
OS : ubuntu14.04

Error:
running install
running build
make -C mitielib
make[1]: Entering directory `/home/administrator/MITIE-master/mitielib'
Compiling src/mitie.cpp
make[1]: g++: Command not found
make[1]: *** [src/mitie.o] Error 127
make[1]: Leaving directory `/home/administrator/MITIE-master/mitielib'
make: *** [mitielib] Error 2
Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    'License :: Boost License',
  File "/home/administrator/anaconda3/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/administrator/anaconda3/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/administrator/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/administrator/anaconda3/lib/python3.5/distutils/command/install.py", line 539, in run
    self.run_command('build')
  File "/home/administrator/anaconda3/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/administrator/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 10, in run
    subprocess.check_call(['make', 'mitielib'])
  File "/home/administrator/anaconda3/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'mitielib']' returned non-zero exit status 2

**Comment by davisking** [comment]
Read the error message.  It says you don't have g++ installed.  You need a compiler.
