### ISSUE TITLE
How to use mitie in Mac, I got AttributeError: module 'mitie' has no attribute 'total_word_feature_extractor'

### ISSUE THREAD

**Issue by Juliesh** [mit-nlp/MITIE#171]
My environment is Mac + Python 3.6.4
After I run the following commands in terminal:
cd mitielib
mkdir build
cd build
cmake ..
cmake --build . --config Release --target install
There is no lib or dll generated.
When I use mitie in code, I can import, but I got this problem:
AttributeError: module 'mitie' has no attribute 'total_word_feature_extractor'
I checked, the mitie.py have class total_word_feature_extractor, why it can not be called?
Please help me, thanks a lot.

The error stack is:
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/train.py", line 125, in <module>
    do_train(config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/train.py", line 111, in do_train
    trainer = Trainer(config, component_builder)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/model.py", line 131, in __init__
    component_name, config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/components.py", line 301, in create_component
    component = registry.create_component_by_name(component_name, config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/registry.py", line 164, in create_component_by_name
    return component_clz.create(config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/utils/mitie_utils.py", line 42, in create
    return MitieNLP(config["mitie_file"], mitie.total_word_feature_extractor(config["mitie_file"]))
AttributeError: module 'mitie' has no attribute 'total_word_feature_extractor'
`

**Comment by davisking** [comment]
Fill out the issue template.
