### ISSUE TITLE
Where can I get total_word_feature_extractor.dat file?

### ISSUE THREAD

**Issue by justin4ai** [mit-nlp/MITIE#219]
Hello, I am trying to check the feasibility whether it would work to use MITIE as a negative word/phrase detector.
However, seemingly ```total_word_feature_extractor.dat``` file has vanished while it used to have been provided by your repository - it might be not though!

I'm quite new to NLP, especially using MITIE so I followed certain template code from google as a reference:

```python
import mitie

model_path = "MITIE-models/english/total_word_feature_extractor.dat"
word_feature_extractor = mitie.total_word_feature_extractor(model_path)

trainer = mitie.text_categorizer_trainer(model_path)
trainer.add_labeled_text("The employee must work overtime without additional pay.", "negative")
trainer.add_labeled_text("Employees are entitled to annual leave as per company policy.", "neutral")
trainer.add_labeled_text("All disputes shall be resolved by the employer's discretion.", "negative")


print("Training the model...")
model = trainer.train()


model.save_to_disk("./negative_phrase_categorizer.dat")


text_categorizer = mitie.text_categorizer("negative_phrase_categorizer.dat")
test_sentence = "The employer reserves the right to amend terms at any time."
predicted_label, confidence = text_categorizer(test_sentence)

print(f"Predicted Label: {predicted_label}, Confidence: {confidence}")
```

And the error messages are like this:

```
Error loading MITIE model file: MITIE-models/english/total_word_feature_extractor.dat
Unable to open MITIE-models/english/total_word_feature_extractor.dat for reading.
Traceback (most recent call last):
  File "/home/nas4_user/seungillee/justin_intern/secure-your-contract/LLMs/mitie_finetune.py", line 5, in <module>
    word_feature_extractor = mitie.total_word_feature_extractor(model_path)
  File "/home/seungillee/.local/lib/python3.9/site-packages/mitie/mitie.py", line 831, in __init__
    raise Exception("Unable to load total_word_feature_extractor detector from " + to_default_str_type(filename))
Exception: Unable to load total_word_feature_extractor detector from MITIE-models/english/total_word_feature_extractor.dat
```

I would greatly appreciate your help!

**Comment by davisking** [comment]
It's still there.  The instructions on the front page link to it https://github.com/mit-nlp/MITIE?tab=readme-ov-file#initial-setup

**Comment by justin4ai** [comment]
Oh I see, I thought it would be there separated from others according to one old reference. It works, thanks for your great work!
