### ISSUE TITLE
python 3 error

### ISSUE THREAD

**Issue by mikeatm** [mit-nlp/MITIE#61]
Can MITIE work with python 3? 
this is what i get if i try one of the train_ner examples:

```
Traceback (most recent call last):
  File "p3train.py", line 11, in <module>
    trainer = ner_trainer(u"../../MITIE-models/english/total_word_feature_extractor.dat")
  File "/home/data/experim/MITIE/examples/python/../../mitielib/mitie.py", line 403, in __init__
    self.__obj = _f.mitie_create_ner_trainer(filename)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
Exception ignored in: <bound method ner_trainer.__del__ of <mitie.ner_trainer object at 0x7fa2bdeb8828>>
Traceback (most recent call last):
  File "/home/data/experim/MITIE/examples/python/../../mitielib/mitie.py", line 409, in __del__
    self.__mitie_free(self.__obj)
AttributeError: 'ner_trainer' object has no attribute '_ner_trainer__mitie_free'
```

**Comment by lopuhin** [comment]
@mikeatm MITIE has basic python 3 support. I guess you need to encode ``filename``, which is a string, to bytes: 
```
trainer = ner_trainer(u"../../MITIE-models/english/total_word_feature_extractor.dat".encode('utf8'))
```
