### ISSUE TITLE
AttributeError: function 'mitie_load_text_categorizer_pure_model_without_feature_extractor' not found

### ISSUE THREAD

**Issue by A-tanveer** [mit-nlp/MITIE#96]
built mitie on windows following these instructions
```
mkdir build
cd build
cmake ..
cmake --build . --config Release --target install
```
but running examples raise these error.

```
G:\MITIE\examples\python>python ner.py
Traceback (most recent call last):
  File "ner.py", line 14, in <module>
    from mitie import *
  File "G:\MITIE\examples\python/../../mitielib\mitie.py", line 665, in <module>
    _f.mitie_load_text_categorizer_pure_model_without_feature_extractor.restype = ctypes.c_void_p
  File "C:\Program Files (x86)\python-2.7\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Program Files (x86)\python-2.7\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'mitie_load_text_categorizer_pure_model_without_feature_extractor' not found
```

**Comment by davisking** [comment]
ner.py doesn't call any text categorizer functions. So I don't see how you could get that error by running that example.  Unless you modified the ner.py code.  Did you modify it?

**Comment by A-tanveer** [comment]
no i haven't modified anything. every example gives this error.

**Comment by davisking** [comment]
Actually, maybe this is a python ctypes error.  Do you have an old MITIE shared library sitting around?  That could explain it.

**Comment by abubakarsohail** [comment]
Hey @davisking I am facing the same error after building MITIE again.
`C:\Users\Abu Bakar Sohail\Desktop\FYP\restaurant-bot>python -m rasa_nlu.train -c config_mitie.json
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build\bdist.win32\egg\rasa_nlu\train.py", line 67, in <module>
  File "build\bdist.win32\egg\rasa_nlu\train.py", line 56, in do_train
  File "build\bdist.win32\egg\rasa_nlu\train.py", line 30, in create_trainer
  File "build\bdist.win32\egg\rasa_nlu\trainers\mitie_trainer.py", line 2, in <module>
  File "mitie.py", line 665, in <module>
    _f.mitie_load_text_categorizer_pure_model_without_feature_extractor.restype = ctypes.c_void_p
  File "C:\Python27\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'mitie_load_text_categorizer_pure_model_without_feature_extractor' not found`

**Comment by davisking** [comment]
Oops.  Looks like some functions were missing export statements.  Try it now.

**Comment by abubakarsohail** [comment]
Thanks @davisking. Worked like a charm.

**Comment by A-tanveer** [comment]
It worked! Thank you very much!

**Comment by davisking** [comment]
No problem.  Thanks for reporting this bug :)
